Repository icgc-argo/platform-api, pull requests merged in 2020-06, with the labels that each got.

#230 update to 1.14.0
  package-lock.json
  package.json
  src/schemas/Clinical/index.ts
Labels: 1.14.0

#231 Master mergeback
  package-lock.json
  package.json
Labels: 1.14.0

#236 Master mergeback
  package.json
Labels: 1.15.0

#244 rc/1.17.0
  .github/pull_request_template.md
  .idea/copyright/oicr_agpl3.xml
  .idea/copyright/profiles_settings.xml
  Jenkinsfile.groovy
  compose/fileCentricEsInit.ts
  compose/programDashboardEsInit.ts
  jest.config.js
  package.json
  src/app.ts
  src/config.ts
  src/constants/clinical.js
  src/global-fetch.d.ts
  src/index.ts
  src/routes/clinical-proxy.ts
  src/routes/kafka-rest-proxy.ts
  src/schemas/Arranger/index.test.ts
  src/schemas/Arranger/index.ts
  src/schemas/Arranger/initArrangerMetadata.ts
  src/schemas/Clinical/gqlTypeDefs.ts
  src/schemas/Clinical/index.ts
  src/schemas/Helpdesk/gqlTypeDefs.ts
  src/schemas/Helpdesk/index.ts
  src/schemas/Helpdesk/jiraRequests.ts
  src/schemas/Program/index.js
  src/schemas/ProgramDonorSummary/gqlTypeDefs.ts
  src/schemas/ProgramDonorSummary/index.ts
  src/schemas/ProgramDonorSummary/resolvers/index.ts
  src/schemas/ProgramDonorSummary/resolvers/summaryEntries.ts
  src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts
  src/schemas/ProgramDonorSummary/resolvers/types.ts
  src/schemas/User/index.ts
  src/schemas/costDirectiveTypeDef.js
  src/schemas/customScalars.js
  src/services/clinical/index.js
  src/services/ego/index.js
  src/services/elasticsearch/index.ts
  src/services/programService/index.js
  src/services/reCaptcha/index.ts
  src/services/vault/index.ts
  src/utils/egoTokenUtils.ts
  src/utils/grpcUtils.js
  src/utils/logger.ts
  src/utils/restUtils.js
Labels: 1.17.0

#252 Master mergeback 2.1.0
  package.json
Labels: 2.1.0

#256 Master mergeback 2.2.0
  package.json
Labels: 2.2.0

#277 Rc/3.3.0
  compose/donors.json
  package.json
  src/config.ts
  src/routes/clinical-proxy.ts
  src/schemas/ProgramDonorSummary/gqlTypeDefs.ts
  src/schemas/ProgramDonorSummary/resolvers/summaryStats.ts
  src/schemas/ProgramDonorSummary/resolvers/types.ts
  src/services/clinical/index.js
Labels: 3.3.0

#278 Master mergeback 3.3.0
  package.json
Labels: 3.3.0
